/**
  Predefined thread exit codes.
*/

#pragma once
#include <windows.h>

const  DWORD  EXIT_THREAD_E_FIRST = 0xFFFFF000;
static DWORD  EXIT_THREAD_E_LAST  = EXIT_THREAD_E_FIRST;
//==
const DWORD EXIT_THREAD_S_OK          = EXIT_THREAD_E_LAST++;
const DWORD EXIT_THREAD_S_QUIT        = EXIT_THREAD_E_LAST++;
const DWORD EXIT_THREAD_S_TERMINATE   = EXIT_THREAD_E_LAST++;
const DWORD EXIT_THREAD_E_NOTEXIST    = EXIT_THREAD_E_LAST++;
const DWORD EXIT_THREAD_E_ERROR       = EXIT_THREAD_E_LAST++;
const DWORD EXIT_THREAD_E_INVALIDARG  = EXIT_THREAD_E_LAST++;
